backend:
  name: github
  branch: staging
  repo: gilbertlucas46/cauayanresort
  squash_merges: true
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: static/img/uploads
public_folder: /img/uploads


collections:
  - name: "accommodation"
    label: "Accommodations"
    description: "Accommodations Pages"
    folder: "src/villas"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Size", name: "size", widget: "string" }
      - { label: About Description, name: desc, widget: 'markdown' }
      
      
