backend:
  name: github
  branch: staging
  repo: gilbertlucas46/cauayanresort
  squash_merges: true
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: "navigation"
    label: "All Navigation"
    description: "All Navigation"
    folder: "src/navigation"
    create: true
    fields:
      - { label: "Template Key", name: "key", widget: "hidden", default: "navigation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: Cauayan Logo, name: cauayan, required: false, hint: "Logo in navigation", widget: image, }
      - { label: Book button, name: bookbutton, required: false, hint: "Floating Book Button", widget: image, }
      - {
          label: Top Contact,
          name: topcontact,
          required: false,
          widget: object,
          fields:
            [
              {
                label: Phone,
                name: phone,
                required: false,
                widget: list,
                fields:
                  [
                    { label: Number, name: num,  widget: number },
                  ],
              },
              { label: Email, name: email,  widget: string },
              { label: Address, name: add,  widget: string },
            ],
        }
      - {
          label: Top Navigation,
          name: topnav,
          required: false,
          widget: list,
          fields:
            [
                { label: Title, name: title,  widget: string },
                { label: Link, name: link,  widget: string },
            ],
        }
      - {
          label: Footer Navigation,
          name: footernav,
          required: false,
          widget: list,
          fields:
            [
              {
                label: Cauayan Logo,
                name: cauayan,
                required: false,
                hint: "Logo in footer",
                widget: image,
              },
              {
                label: Newsletter,
                name: newsletter,
                required: false,
                widget: object,
                fields:
                  [
                    { label: Message, name: msg,  widget: string },
                  ],
              },
              {
                label: Quick Links,
                name: qlinks,
                required: false,
                widget: list,
                fields:
                  [
                    { label: Title, name: title,  widget: string },
                    { label: URL, name: url,  widget: string },
                  ],
              },
              {
                label: Contact Details,
                name: contact,
                required: false,
                widget: list,
                fields:
                  [
                    { label: Address, name: add,  widget: string },
                    {
                      label: Phone,
                      name: phone,
                      required: false,
                      widget: list,
                      fields:
                        [
                          { label: Number, name: num,  widget: number },
                        ],
                    },
                    { label: Email, name: email,  widget: string },
                  ],
              },
              {
                label: Footer BG,
                name: footerbg,
                widget: object,
                fields:
                  [
                    {
                      label: Desktop view image,
                      name: desktop,
                      required: false,
                      widget: image,
                    },
                    {
                      label: Tablet view image,
                      name: tablet,
                      required: false,
                      widget: image,
                    },
                    {
                      label: Mobile view image,
                      name: mobile,
                      required: false,
                      widget: image,
                    },
                  ],
                },
              {
                label: Trip Advisory Logo,
                name: advisory,
                required: false,
                hint: "Logo in footer",
                widget: image,
              }
            ],
        }
      -  {
            label: Social Channels,
            name: social,
            widget: list,
            fields:
              [
                {
                  label: Social Links,
                  name: name,
                  required: false,
                  widget: "string",
                },
                {
                  label: Social Icons,
                  name: icons,
                  required: false,
                  widget: image,
                }
              ],
          }

  - name: "accommodation"
    label: "Accommodations"
    description: "Accommodations Pages"
    folder: "src/villas"
    create: true
    fields:
      - { label: "Villa Sort Number", name: "villasort", widget: "number" }
      - {
          label: Image,
          name: image,
          required: false,
          hint: "Image of the accommodation/unit/room",
          widget: image,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Size", name: "size", widget: "string" }
      - { label: "About Description", name: desc, widget: 'markdown' }
      - {
          label: Image Slider,
          name: slider,
          required: true,
          widget: list,
          fields:
            [
              {
                label: Image,
                name: image,
                required: false,
                hint: "This is the images in that slides in villa view",
                widget: image,
              }
            ]
          }

  - name: "mainpages"
    label: "Main Pages"
    description: "Main Pages"
    folder: "src/pages/main"
    create: false
    fields:
      - { label: "Template Key", name: "key", widget: "hidden", default: "mainpages" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: Home Page,
          name: home,
          required: false,
          widget: object,
          fields:
            [
              { label: Title, name: title,  widget: string },
                {
                  label: Sliders,
                  name: slider,
                  required: true,
                  widget: list,
                  fields:
                    [
                      {
                        label: Image,
                        name: image,
                        required: false,
                        hint: "This is the images in that slides in home page",
                        widget: image,
                      },
                      { label: Title, name: title,  widget: string },
                      { label: Caption, name: caption, widget: string },
                      { label: Button, name: button,  widget: string },
                      { label: URL, name: url, widget: string }
                    ],
                },
                {
                  label: Image Nav,
                  name: imagenav,
                  widget: list,
                  fields:
                    [
                      {
                        label: Image,
                        name: image,
                        required: false,
                        hint: "image nav for home page",
                        widget: image,
                      },
                      { label: Title, name: title,  widget: string },
                      { label: URL, name: url, widget: string }
                    ],
                },
                {
                  label: Video,
                  name: video,
                  widget: object,
                  fields:
                    [
                      {
                        label: Button,
                        name: button,
                        required: false,
                        hint: "Play Button",
                        widget: image,
                      },
                      {
                        label: Video Preview Desktop,
                        name: desktop,
                        required: false,
                        hint: "Video Preview",
                        widget: image,
                      },
                      {
                        label: Video Preview Tablet,
                        name: tablet,
                        required: false,
                        hint: "Video Preview for Tablet",
                        widget: image,
                      },
                      {
                        label: Video Preview Mobile,
                        name: mobile,
                        required: false,
                        hint: "Video Preview for Mobile",
                        widget: image,
                      },
                      { label: Title, name: title,  widget: string },
                      { label: Sub Title, name: subtitle,  widget: string },
                      { label: Description, name: desc, widget: markdown },
                      { label: Video Embed, name: video, widget: markdown }
                    ],
                },
                {
                  label: Short Intro About,
                  name: intro,
                  widget: object,
                  fields:
                    [
                      {
                        label: Island View,
                        name: island,
                        required: false,
                        hint: "Top View Of Island",
                        widget: image,
                      },
                      { label: Title, name: title,  widget: string },
                      { label: Description, name: desc, widget: markdown },
                      { label: Read more links to, name: link,  widget: string },
                    ],
                },
                {
                  label: Contact Form BG,
                  name: contact,
                  widget: object,
                  fields:
                    [
                      {
                        label: Desktop view image,
                        name: desktop,
                        required: false,
                        widget: image,
                      },
                      {
                        label: Tablet view image,
                        name: tablet,
                        required: false,
                        widget: image,
                      },
                      {
                        label: Mobile view image,
                        name: mobile,
                        required: false,
                        widget: image,
                      },
                    ],
                },
            ],
        }
      - {
          label: About Page,
          name: about,
          required: false,
          widget: object,
          fields:
            [
              { label: Title, name: title,  widget: string },
              {
                label: Top Image,
                name: tmage,
                required: false,
                hint: "Top Image visible at the bottom of the navigation",
                widget: image,
              },
              {
                label: Images,
                name: images,
                required: false,
                widget: list,
                fields:
                  [
                    {
                      label: Image,
                      name: image,
                      required: false,
                      hint: "images for about page",
                      widget: image,
                    },
                    
                  ],
              },
              { label: About Description, name: desc, widget: 'markdown' },
              { label: Philosophy Content, name: 'phcontent', widget: 'markdown' },
              {
                label: Video BG,
                name: videobg,
                required: false,
                hint: "Video BG",
                widget: image,
              },
              { label: "Video Source", name: "source", widget: "text"}
            ],
        }
      - {
          label: Our Villas Page,
          name: ourvillas,
          required: false,
          widget: object,
          fields:
            [
              { label: Title, name: title,  widget: string },
              { label: About Description, name: desc, widget: 'markdown' },
            ],
        }