backend:
  name: github
  branch: staging
  repo: gilbertlucas46/cauayanresort
  squash_merges: false
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: "pages"
    label: "Page"
    description: "Page"
    folder: "src/pages/main"
    create: false
    fields:
      - { label: "Template Key", name: "key", widget: "hidden", default: "mainpages" }
      - {
          label: Home,
          name: home,
          widget: object,
          fields:
            [
              { label: Title, name: title,  widget: string }
            ],
        }
