backend:
  name: github
  branch: staging
  repo: gilbertlucas46/cauayanresort
  squash_merges: true
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: "pages"
    label: "Pages"
    description: "Lists of all Main pages"
    folder: "src/pages/main"
    expandItems: false
    create: true
    fields:
      - { label: "Home Page", name: "home", widget: "hidden", default: "home" }
      - {
          label: Home,
          name: home,
          widget: object,
          expandItems: false,
          fields:
            [
              {
                label: Sliders,
                name: slider,
                required: true,
                widget: list,
                fields:
                  [
                    {
                      label: Image,
                      name: image,
                      required: false,
                      hint: "This is the images in that slides in home page",
                      widget: image,
                    },
                    { label: Title, name: title, required: true, widget: string },
                    { label: Caption, name: caption, widget: string },
                    { label: Button, name: button, required: true, widget: string },
                    { label: URL, name: url, widget: string }
                  ],
              },
            ],
            [
              {
                label: Image Navigation,
                name: imagenav,
                required: true,
                widget: list,
                fields:
                  [
                    {
                      label: Image,
                      name: image,
                      required: false,
                      hint: "navigation image in home page",
                      widget: image,
                    },
                    { label: Title, name: title, required: true, widget: string },
                    { label: URL, name: url, widget: string }
                  ],
              },
            ]
        }