backend:
  name: github
  branch: staging
  repo: gilbertlucas46/cauayanresort
  squash_merges: true
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: "home"
    label: "Home Page"
    description: "Home Page"
    folder: "src/pages/main"
    create: true
    fields:
      - { label: "Template Key", name: "key", widget: "hidden", default: "mainpages" }
      - {
          label: Video,
          name: video,
          widget: object,
          fields:
            [
              { label: "Title", name: "title", widget: "string" }
              {
                label: Play Button,
                name: button,
                required: false,
                hint: "Play button for home page",
                widget: image,
              },
              {
                label: Video BG,
                name: videobg,
                required: false,
                hint: "Video BG",
                widget: image,
              },
              { label: Title, name: title,  widget: string },
              { label: Caption, name: caption,  widget: string },
              {label: "Description", name: "description", widget: "text"},
              {label: "Video Source", name: "source", widget: "text"}
            ],
        }
