backend:
  name: github
  branch: staging
  repo: gilbertlucas46/cauayanresort
  squash_merges: true
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: "home"
    label: "Home Page"
    description: "Home Page"
    folder: "src/pages/main"
    create: true
    fields:
      - { label: "Template Key", name: "key", widget: "hidden", default: "mainpages" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: Sliders,
          name: slider,
          required: true,
          widget: list,
          fields:
            [
              {
                label: Image,
                name: image,
                required: false,
                hint: "This is the images in that slides in home page",
                widget: image,
              },
              { label: Title, name: title,  widget: string },
              { label: Caption, name: caption, widget: string },
              { label: Button, name: button,  widget: string },
              { label: URL, name: url, widget: string }
            ],
        }
      - {
          label: Image Nav,
          name: imagenav,
          widget: list,
          fields:
            [
              {
                label: Image,
                name: image,
                required: false,
                hint: "image nav for home page",
                widget: image,
              },
              { label: Title, name: title,  widget: string },
              { label: URL, name: url, widget: string }
            ],
        }
      - {
          label: Video,
          name: video,
          widget: object,
          fields:
            [
              {
                label: Play Button,
                name: button,
                required: false,
                hint: "Play button for home page",
                widget: image,
              },
              {
                label: Video BG,
                name: videobg,
                required: false,
                hint: "Video BG",
                widget: image,
              },
              { label: Title, name: title,  widget: string },
              { label: Caption, name: caption,  widget: string },
              {label: "Description", name: "description", widget: "text"},
              {label: "Video Source", name: "source", widget: "text"}
            ],
        }
  - name: "pages"
      label: "Pages"
      files:
        - file: "src/pages/about/index.md"
          label: "About"
          name: "about"
          fields:
            - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
            - { label: "Title", name: "title", widget: "string" }
            - {
                label: "Main Image",
                name: "mainImage",
                widget: "object",
                fields:
                  [
                    { label: "Image", name: "image", widget: "image" },
                    { label: "Image Description", name: "imageAlt", widget: "string" },
                  ],
              }
            - { label: "Body", name: "body", widget: "markdown" }
            - {
                label: "Image Gallery",
                name: "gallery",
                widget: "list",
                fields:
                  [
                    { label: "Image", name: "image", widget: "image" },
                    { label: "Image Description", name: "imageAlt", widget: "string" },
                  ],
              }
            - { label: "Developer Groups", name: "developerGroups", widget: "markdown" }
            - {
                label: "Meetup Organizers",
                name: "organizers",
                widget: "object",
                fields:
                  [
                    { label: "Title", name: "title", widget: "string" },
                    {
                      label: "Images",
                      name: "gallery",
                      widget: "list",
                      fields:
                        [
                          { label: "Name", name: "name", widget: "string" },
                          { label: "Image", name: "image", widget: "image" },
                          { label: "Image Description", name: "imageAlt", widget: "string" },
                        ],
                    },
                  ],
              }
