backend:
  name: github
  branch: staging
  repo: gilbertlucas46/cauayanresort
  squash_merges: true
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: "pages"
    label: "Pages"
    description: "Lists of all Main pages"
    folder: "src/pages/main"
    create: true
    fields:
      - { label: "Main Pages", name: "templateKey", widget: "hidden", default: "mainpages" }
      - { label: "Page Name", name: "pagname", widget: "string" }
      - {
          label: "Home Page",
          name: "home",
          required: true,
          widget: "object",
          fields:
            [
              { label: "Name", name: "name", widget: "string" },
              { label: "Google Maps Link", name: "mapsLink", widget: "string" },
              { label: "Latitude", name: "mapsLatitude", widget: "number", valueType: "float" },
              { label: "Longitude", name: "mapsLongitude", widget: "number", valueType: "float" },
              { label: "Page", name: "pagename", widget: "string", default: "home" }
              field:
                {
                  label: Sliders,
                  name: slider,
                  required: true,
                  widget: list,
                  fields:
                    [
                      { label: Title, name: title, required: true, widget: string },
                      {
                        label: Image,
                        name: image,
                        required: false,
                        hint: "This is the images in that slides in home page",
                        widget: image,
                      },
                      {
                        label: Links,
                        name: links,
                        required: false,
                        widget: list,
                        fields:
                          [
                            { label: Text, name: name, widget: string },
                            { label: URL, name: url, widget: string },
                          ],
                      },
                    ],
                }
            ],
            
        }