backend:
  name: github
  branch: staging
  repo: gilbertlucas46/cauayanresort
  squash_merges: true
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: "navigation"
    label: "All Navigation"
    description: "All Navigation"
    folder: "src/navigation"
    create: true
    fields:
      - { label: "Template Key", name: "key", widget: "hidden", default: "navigation" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: Top Navigation,
          name: topnav,
          required: false,
          widget: list,
          fields:
            [
                { label: Title, name: title,  widget: string },
                { label: Link, name: link,  widget: string },
            ],
        }
      - {
          label: Footer Navigation,
          name: footernav,
          required: false,
          widget: list,
          fields:
            [
              {
                label: Cauayan Logo,
                name: cauayan,
                required: false,
                hint: "Logo in footer",
                widget: image,
              },
              {
                label: Newsletter,
                name: newsletter,
                required: false,
                widget: object,
                fields:
                  [
                    { label: Message, name: msg,  widget: string },
                  ],
              },
              {
                label: Quick Links,
                name: qlinks,
                required: false,
                widget: list,
                fields:
                  [
                    { label: Title, name: title,  widget: string },
                    { label: URL, name: url,  widget: string },
                  ],
              },
              {
                label: Contact Details,
                name: contact,
                required: false,
                widget: list,
                fields:
                  [
                    { label: Address, name: add,  widget: string },
                    {
                      label: Phone,
                      name: phone,
                      required: false,
                      widget: list,
                      fields:
                        [
                          { label: Number, name: num,  widget: number },
                        ],
                    },
                    { label: Email, name: email,  widget: string },
                  ],
              },
              {
                label: Trip Advisory Logo,
                name: advisory,
                required: false,
                hint: "Logo in footer",
                widget: image,
              }
            ],
        }

  - name: "accommodation"
    label: "Accommodations"
    description: "Accommodations Pages"
    folder: "src/villas"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Size", name: "size", widget: "string" }
      - { label: About Description, name: desc, widget: 'markdown' }
  - name: "mainpages"
    label: "Main Pages"
    description: "Main Pages"
    folder: "src/pages/main"
    create: true
    fields:
      - { label: "Template Key", name: "key", widget: "hidden", default: "mainpages" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: Home,
          name: home,
          required: false,
          widget: object,
          fields:
            [
              { label: Title, name: title,  widget: string },
                {
                  label: Sliders,
                  name: slider,
                  required: true,
                  widget: list,
                  fields:
                    [
                      {
                        label: Image,
                        name: image,
                        required: false,
                        hint: "This is the images in that slides in home page",
                        widget: image,
                      },
                      { label: Title, name: title,  widget: string },
                      { label: Caption, name: caption, widget: string },
                      { label: Button, name: button,  widget: string },
                      { label: URL, name: url, widget: string }
                    ],
                },
                {
                  label: Image Nav,
                  name: imagenav,
                  widget: list,
                  fields:
                    [
                      {
                        label: Image,
                        name: image,
                        required: false,
                        hint: "image nav for home page",
                        widget: image,
                      },
                      { label: Title, name: title,  widget: string },
                      { label: URL, name: url, widget: string }
                    ],
                }
            ],
        }
      - {
          label: About,
          name: about,
          required: false,
          widget: object,
          fields:
            [
              {
                label: Images,
                name: images,
                required: false,
                widget: list,
                fields:
                  [
                    {
                      label: Image,
                      name: image,
                      required: false,
                      hint: "images for about page",
                      widget: image,
                    },
                    
                  ],
              },
              { label: About Description, name: desc, widget: 'markdown' },
              { label: Philosophy Content, name: 'phcontent', widget: 'markdown' },
              {
                label: Video BG,
                name: videobg,
                required: false,
                hint: "Video BG",
                widget: image,
              },
              { label: "Video Source", name: "source", widget: "text"}
            ],
        }